rm -rf monoenergetic_2.5MeV_electrons_PI_doped_25percent.root
rm -rf low_energy_electrons_doped_75percent.root
rm -rf low_energy_electrons_doped_50percent.root
rm -rf low_energy_electrons_PI_doped_75percent.root
